"""Fallback game content used to seed or hydrate admin-managed items."""

COCHON_PENDU_WORDS = [
    'PURIN',
    'TRUFFES',
    'TIRELIRE',
    'JAMBON',
    'VETERINAIRE',
    'AVOINE',
    'COTE',
    'PELOTON',
    'SAUCISSON',
    'ENDURANCE',
    'PARIS',
    'FERMIER',
    'PRAIRIE',
]

CEREALS = {
    'mais': {
        'name': 'Maïs', 'emoji': '🌽', 'cost': 5,
        'description': 'Base équilibrée, petit boost partout',
        'hunger_restore': 20, 'energy_restore': 5,
        'stats': {'vitesse': 0.5, 'endurance': 0.5, 'agilite': 0.5, 'force': 0.5, 'intelligence': 0.5, 'moral': 0.5},
        'weight_delta': 0.5,
        'valeur_fourragere': 100,
    },
    'orge': {
        'name': 'Orge', 'emoji': '🌾', 'cost': 8,
        'description': '+Endurance +Force',
        'hunger_restore': 30, 'energy_restore': 8,
        'stats': {'endurance': 2.0, 'force': 1.5, 'vitesse': 0.3},
        'weight_delta': 0.9,
        'valeur_fourragere': 97,
    },
    'ble': {
        'name': 'Blé', 'emoji': '🌿', 'cost': 10,
        'description': '+Force +Vitesse',
        'hunger_restore': 25, 'energy_restore': 5,
        'stats': {'force': 2.0, 'vitesse': 1.5, 'endurance': 0.5},
        'weight_delta': 0.8,
        'valeur_fourragere': 105,
    },
    'seigle': {
        'name': 'Seigle', 'emoji': '🌱', 'cost': 7,
        'description': '+Agilité +Intelligence',
        'hunger_restore': 20, 'energy_restore': 5,
        'stats': {'agilite': 2.0, 'intelligence': 1.5},
        'weight_delta': 0.3,
        'valeur_fourragere': 102,
    },
    'triticale': {
        'name': 'Triticale', 'emoji': '🍃', 'cost': 9,
        'description': '+Vitesse +Endurance',
        'hunger_restore': 25, 'energy_restore': 10,
        'stats': {'vitesse': 2.0, 'endurance': 1.5, 'moral': 0.5},
        'weight_delta': 0.4,
        'valeur_fourragere': 100,
    },
    'avoine': {
        'name': 'Avoine', 'emoji': '🥣', 'cost': 6,
        'description': '+Moral +Agilité — récupération',
        'hunger_restore': 15, 'energy_restore': 15,
        'stats': {'moral': 2.5, 'agilite': 1.0},
        'weight_delta': 0.2,
        'valeur_fourragere': 82,
    },
}

TRAININGS = {
    'sprint': {
        'name': 'Sprint', 'emoji': '💨',
        'description': 'Course courte et explosive',
        'energy_cost': 25, 'hunger_cost': 10,
        'stats': {'vitesse': 0.6, 'endurance': 0.2},
        'weight_delta': -0.7,
        'min_happiness': 20,
    },
    'cross': {
        'name': 'Cross-country', 'emoji': '🏃',
        'description': "Longue distance, mental d'acier",
        'energy_cost': 35, 'hunger_cost': 15,
        'stats': {'endurance': 0.6, 'force': 0.2, 'vitesse': 0.1},
        'weight_delta': -1.0,
        'min_happiness': 20,
    },
    'obstacles': {
        'name': "Parcours d'obstacles", 'emoji': '🏅',
        'description': 'Agilité et réflexes',
        'energy_cost': 30, 'hunger_cost': 10,
        'stats': {'agilite': 0.6, 'intelligence': 0.2},
        'weight_delta': -0.6,
        'min_happiness': 30,
    },
    'sparring': {
        'name': 'Sparring', 'emoji': '🥊',
        'description': 'Combat amical, gagne en puissance',
        'energy_cost': 30, 'hunger_cost': 15,
        'stats': {'force': 0.6, 'moral': 0.1, 'endurance': 0.1},
        'weight_delta': 0.2,
        'min_happiness': 30,
    },
    'puzzles': {
        'name': 'Puzzles & Stratégie', 'emoji': '🧩',
        'description': 'Entraînement cérébral',
        'energy_cost': 15, 'hunger_cost': 5,
        'stats': {'intelligence': 0.6, 'moral': 0.2},
        'weight_delta': 0.1,
        'min_happiness': 10,
    },
    'repos': {
        'name': 'Repos & Détente', 'emoji': '😴',
        'description': 'Récupération complète',
        'energy_cost': -40, 'hunger_cost': 5,
        'stats': {'moral': 0.4},
        'weight_delta': 0.5,
        'happiness_bonus': 15,
        'min_happiness': 0,
    },
}

SCHOOL_LESSONS = {
    'strategie': {
        'name': 'Strategie de Virage',
        'emoji': '📐',
        'description': 'Apprendre a lire la piste et garder sa relance au bon moment.',
        'question': 'Dans un virage serre, quelle est la meilleure approche ?',
        'answers': [
            {'text': 'Ralentir legerement puis accelerer en sortie', 'correct': True, 'feedback': 'Bonne lecture. La sortie de virage fait gagner plus de terrain que l entree heroique.'},
            {'text': 'Foncer tout droit et compter sur la chance', 'correct': False, 'feedback': 'La chance ne tient pas la corde tres longtemps.'},
            {'text': 'S arreter pour observer les autres', 'correct': False, 'feedback': 'Observer c est bien, planter ses sabots au milieu de la piste un peu moins.'},
            {'text': 'Suivre le plus bruyant du groupe', 'correct': False, 'feedback': 'Le vacarme n est pas une tactique de course.'},
        ],
        'stats': {'intelligence': 0.5, 'agilite': 0.3},
        'xp': 24,
        'wrong_xp': 6,
        'energy_cost': 10,
        'hunger_cost': 4,
        'min_happiness': 15,
        'happiness_bonus': 5,
        'wrong_happiness_penalty': 6,
    },
    'nutrition': {
        'name': 'Nutrition du Champion',
        'emoji': '🥗',
        'description': 'Comprendre quand manger pour tenir jusqu au sprint final.',
        'question': 'Quel repas prepare le mieux un cochon juste avant la course ?',
        'answers': [
            {'text': 'Un repas equilibre et facile a digerer', 'correct': True, 'feedback': 'Exact. Du carburant utile, pas un festival du bidou.'},
            {'text': 'Une fondue XXL servie tres chaude', 'correct': False, 'feedback': 'Excellente idee pour une sieste, beaucoup moins pour un depart.'},
            {'text': 'Aucun repas pour courir leger', 'correct': False, 'feedback': 'Leger, oui. Debout au depart, beaucoup moins sur.'},
            {'text': 'Trois desserts et un soda surprise', 'correct': False, 'feedback': 'Ton cochon applaudit, son endurance beaucoup moins.'},
        ],
        'stats': {'endurance': 0.4, 'moral': 0.2},
        'xp': 22,
        'wrong_xp': 5,
        'energy_cost': 8,
        'hunger_cost': 3,
        'min_happiness': 10,
        'happiness_bonus': 4,
        'wrong_happiness_penalty': 5,
    },
    'mental': {
        'name': 'Mental d Acier',
        'emoji': '🧠',
        'description': 'Gerer la pression, la foule et les petits cochons qui fanfaronnent.',
        'question': 'Comment garder son sang-froid juste avant le depart ?',
        'answers': [
            {'text': 'Respirer, se concentrer et ignorer la provoc', 'correct': True, 'feedback': 'Parfait. Le calme fait plus de degats que les cris.'},
            {'text': 'Repondre a toutes les moqueries', 'correct': False, 'feedback': 'Ton cochon gagne peut-etre une dispute, pas une course.'},
            {'text': 'Dormir sur la ligne de depart', 'correct': False, 'feedback': 'Repos mal place. Ambiance sieste, resultat desastreux.'},
            {'text': 'Paniquer tres fort tres tot', 'correct': False, 'feedback': 'Technique peu recommandee par l academie porcine.'},
        ],
        'stats': {'moral': 0.4, 'intelligence': 0.3},
        'xp': 26,
        'wrong_xp': 6,
        'energy_cost': 9,
        'hunger_cost': 3,
        'min_happiness': 20,
        'happiness_bonus': 6,
        'wrong_happiness_penalty': 4,
    },
    'video': {
        'name': 'Analyse Video',
        'emoji': '🎥',
        'description': 'Revision des departs fulgurants et des depassements bien sentis.',
        'question': 'Quel detail faut-il surveiller sur une rediffusion de course ?',
        'answers': [
            {'text': 'Le timing des accelerations et les ouvertures dans le trafic', 'correct': True, 'feedback': 'Exact. Les details repetes font les champions reguliers.'},
            {'text': 'La couleur des bottes du soigneur', 'correct': False, 'feedback': 'Elegant, mais pas franchement decisif sur 400 metres.'},
            {'text': 'Le nombre de spectateurs au premier rang', 'correct': False, 'feedback': 'Flatteur pour l ego, inutile pour la trajectoire.'},
            {'text': 'La meilleure pose pour la photo d arrivee', 'correct': False, 'feedback': 'D abord la course, ensuite la couverture de magazine.'},
        ],
        'stats': {'vitesse': 0.3, 'agilite': 0.3, 'intelligence': 0.2},
        'xp': 24,
        'wrong_xp': 6,
        'energy_cost': 11,
        'hunger_cost': 4,
        'min_happiness': 15,
        'happiness_bonus': 5,
        'wrong_happiness_penalty': 5,
    },
}
