"""initial schema

Revision ID: dba87ebffc9d
Revises: 
Create Date: 2026-04-02 11:37:48.565764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba87ebffc9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cereal_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('hunger_restore', sa.Float(), nullable=True),
    sa.Column('energy_restore', sa.Float(), nullable=True),
    sa.Column('weight_delta', sa.Float(), nullable=True),
    sa.Column('valeur_fourragere', sa.Float(), nullable=True),
    sa.Column('stat_vitesse', sa.Float(), nullable=True),
    sa.Column('stat_endurance', sa.Float(), nullable=True),
    sa.Column('stat_agilite', sa.Float(), nullable=True),
    sa.Column('stat_force', sa.Float(), nullable=True),
    sa.Column('stat_intelligence', sa.Float(), nullable=True),
    sa.Column('stat_moral', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('available_from', sa.DateTime(), nullable=True),
    sa.Column('available_until', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('game_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('market_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cereal_key', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('surcharge', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_history_cereal_key'), ['cereal_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_history_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('pig_avatar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('poker_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('buy_in', sa.Integer(), nullable=False),
    sa.Column('pot', sa.Float(), nullable=True),
    sa.Column('current_bet', sa.Float(), nullable=True),
    sa.Column('dealer_seat', sa.Integer(), nullable=True),
    sa.Column('action_seat', sa.Integer(), nullable=True),
    sa.Column('hand_number', sa.Integer(), nullable=True),
    sa.Column('deck_json', sa.Text(), nullable=True),
    sa.Column('community_json', sa.Text(), nullable=True),
    sa.Column('state_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('winner_name', sa.String(length=80), nullable=True),
    sa.Column('winner_odds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('replay_json', sa.Text(), nullable=True),
    sa.Column('preview_segments_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.create_index('ix_race_status_finished', ['status', 'finished_at'], unique=False)

    op.create_table('school_lesson_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('stat_vitesse', sa.Float(), nullable=True),
    sa.Column('stat_endurance', sa.Float(), nullable=True),
    sa.Column('stat_agilite', sa.Float(), nullable=True),
    sa.Column('stat_force', sa.Float(), nullable=True),
    sa.Column('stat_intelligence', sa.Float(), nullable=True),
    sa.Column('stat_moral', sa.Float(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('wrong_xp', sa.Integer(), nullable=True),
    sa.Column('energy_cost', sa.Integer(), nullable=True),
    sa.Column('hunger_cost', sa.Integer(), nullable=True),
    sa.Column('min_happiness', sa.Integer(), nullable=True),
    sa.Column('happiness_bonus', sa.Integer(), nullable=True),
    sa.Column('wrong_happiness_penalty', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('available_from', sa.DateTime(), nullable=True),
    sa.Column('available_until', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('slogan', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('training_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('energy_cost', sa.Integer(), nullable=True),
    sa.Column('hunger_cost', sa.Integer(), nullable=True),
    sa.Column('weight_delta', sa.Float(), nullable=True),
    sa.Column('min_happiness', sa.Integer(), nullable=True),
    sa.Column('happiness_bonus', sa.Integer(), nullable=True),
    sa.Column('stat_vitesse', sa.Float(), nullable=True),
    sa.Column('stat_endurance', sa.Float(), nullable=True),
    sa.Column('stat_agilite', sa.Float(), nullable=True),
    sa.Column('stat_force', sa.Float(), nullable=True),
    sa.Column('stat_intelligence', sa.Float(), nullable=True),
    sa.Column('stat_moral', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('available_from', sa.DateTime(), nullable=True),
    sa.Column('available_until', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_relief_at', sa.DateTime(), nullable=True),
    sa.Column('barn_heritage_bonus', sa.Float(), nullable=True),
    sa.Column('snack_shares_today', sa.Integer(), nullable=True),
    sa.Column('snack_share_reset_at', sa.DateTime(), nullable=True),
    sa.Column('last_daily_reward_at', sa.DateTime(), nullable=True),
    sa.Column('last_truffe_at', sa.DateTime(), nullable=True),
    sa.Column('truffe_plays_today', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_agenda_at', sa.DateTime(), nullable=True),
    sa.Column('agenda_plays_today', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pig_name', sa.String(length=80), nullable=False),
    sa.Column('pig_emoji', sa.String(length=10), nullable=True),
    sa.Column('pig_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('pig_vitesse', sa.Float(), nullable=True),
    sa.Column('pig_endurance', sa.Float(), nullable=True),
    sa.Column('pig_agilite', sa.Float(), nullable=True),
    sa.Column('pig_force', sa.Float(), nullable=True),
    sa.Column('pig_intelligence', sa.Float(), nullable=True),
    sa.Column('pig_moral', sa.Float(), nullable=True),
    sa.Column('pig_weight', sa.Float(), nullable=True),
    sa.Column('pig_rarity', sa.String(length=20), nullable=True),
    sa.Column('pig_max_races', sa.Integer(), nullable=True),
    sa.Column('pig_origin', sa.String(length=30), nullable=True),
    sa.Column('pig_origin_flag', sa.String(length=10), nullable=True),
    sa.Column('starting_price', sa.Float(), nullable=True),
    sa.Column('current_bid', sa.Float(), nullable=True),
    sa.Column('bidder_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('source_pig_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['bidder_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username_attempt', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('route', sa.String(length=120), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_event_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_event_log_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_event_log_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_event_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_event_log_username_attempt'), ['username_attempt'], unique=False)
        batch_op.create_index('ix_auth_event_type_time', ['event_type', 'occurred_at'], unique=False)

    op.create_table('balance_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_before', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('reason_label', sa.String(length=80), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_transaction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_transaction_user_id'), ['user_id'], unique=False)

    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('pig_name', sa.String(length=80), nullable=False),
    sa.Column('bet_type', sa.String(length=20), nullable=True),
    sa.Column('selection_order', sa.String(length=240), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('odds_at_bet', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('winnings', sa.Float(), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.create_index('ix_bet_user_race', ['user_id', 'race_id'], unique=False)

    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['chat_message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_timestamp'), ['timestamp'], unique=False)

    op.create_table('grain_market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cursor_x', sa.Integer(), nullable=True),
    sa.Column('cursor_y', sa.Integer(), nullable=True),
    sa.Column('vitrine_grain', sa.String(length=20), nullable=True),
    sa.Column('vitrine_user_id', sa.Integer(), nullable=True),
    sa.Column('last_move_user_id', sa.Integer(), nullable=True),
    sa.Column('last_move_at', sa.DateTime(), nullable=True),
    sa.Column('last_purchase_at', sa.DateTime(), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_move_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vitrine_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prix_truffes', sa.Float(), nullable=True),
    sa.Column('prix_glands', sa.Float(), nullable=True),
    sa.Column('type_effet', sa.String(length=50), nullable=True),
    sa.Column('valeur_effet', sa.Float(), nullable=True),
    sa.Column('fiabilite', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.Column('vitesse', sa.Float(), nullable=True),
    sa.Column('endurance', sa.Float(), nullable=True),
    sa.Column('agilite', sa.Float(), nullable=True),
    sa.Column('force', sa.Float(), nullable=True),
    sa.Column('intelligence', sa.Float(), nullable=True),
    sa.Column('moral', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('hunger', sa.Float(), nullable=True),
    sa.Column('happiness', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('freshness', sa.Float(), nullable=True),
    sa.Column('ever_bad_state', sa.Boolean(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('races_won', sa.Integer(), nullable=True),
    sa.Column('races_entered', sa.Integer(), nullable=True),
    sa.Column('school_sessions_completed', sa.Integer(), nullable=True),
    sa.Column('max_races', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('origin_country', sa.String(length=30), nullable=True),
    sa.Column('origin_flag', sa.String(length=10), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.Column('death_cause', sa.String(length=30), nullable=True),
    sa.Column('charcuterie_type', sa.String(length=50), nullable=True),
    sa.Column('charcuterie_emoji', sa.String(length=10), nullable=True),
    sa.Column('epitaph', sa.String(length=200), nullable=True),
    sa.Column('challenge_mort_wager', sa.Float(), nullable=True),
    sa.Column('is_injured', sa.Boolean(), nullable=True),
    sa.Column('injury_risk', sa.Float(), nullable=True),
    sa.Column('vet_deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_school_at', sa.DateTime(), nullable=True),
    sa.Column('last_fed_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('comeback_bonus_ready', sa.Boolean(), nullable=True),
    sa.Column('lineage_name', sa.String(length=80), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('lineage_boost', sa.Float(), nullable=True),
    sa.Column('sire_id', sa.Integer(), nullable=True),
    sa.Column('dam_id', sa.Integer(), nullable=True),
    sa.Column('retired_into_heritage', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['avatar_id'], ['pig_avatar.id'], ),
    sa.ForeignKeyConstraint(['dam_id'], ['pig.id'], ),
    sa.ForeignKeyConstraint(['sire_id'], ['pig.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pig', schema=None) as batch_op:
        batch_op.create_index('ix_pig_user_alive', ['user_id', 'is_alive'], unique=False)

    op.create_table('poker_hand_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('hand_number', sa.Integer(), nullable=False),
    sa.Column('pot', sa.Float(), nullable=True),
    sa.Column('winner_ids', sa.Text(), nullable=True),
    sa.Column('hand_results', sa.Text(), nullable=True),
    sa.Column('community_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['poker_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poker_hand_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poker_hand_history_table_id'), ['table_id'], unique=False)

    op.create_table('poker_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('chips', sa.Float(), nullable=True),
    sa.Column('current_bet', sa.Float(), nullable=True),
    sa.Column('has_folded', sa.Boolean(), nullable=True),
    sa.Column('has_acted', sa.Boolean(), nullable=True),
    sa.Column('is_spectator', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('hole_json', sa.Text(), nullable=True),
    sa.Column('vote', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['poker_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'seat', name='uq_poker_table_seat')
    )
    with op.batch_alter_table('poker_player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poker_player_table_id'), ['table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poker_player_user_id'), ['user_id'], unique=False)

    op.create_table('trophy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trophy_key', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('pig_name', sa.String(length=80), nullable=True),
    sa.Column('date_earned', sa.DateTime(), nullable=True),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='ux_trophy_user_code')
    )
    with op.batch_alter_table('trophy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trophy_date_earned'), ['date_earned'], unique=False)
        batch_op.create_index(batch_op.f('ix_trophy_earned_at'), ['earned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trophy_user_id'), ['user_id'], unique=False)

    op.create_table('user_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=280), nullable=False),
    sa.Column('event_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notification_event_key'), ['event_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notification_user_id'), ['user_id'], unique=False)

    op.create_table('course_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pig_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('strategy_profile', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pig_id'], ['pig.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pig_id', 'scheduled_at', name='ux_course_plan_pig_slot')
    )
    with op.batch_alter_table('course_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_plan_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_plan_pig_id'), ['pig_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_plan_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_plan_user_id'), ['user_id'], unique=False)

    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('win_probability', sa.Float(), nullable=False),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('pig_id', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['pig_id'], ['pig.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_index('ix_participant_race', ['race_id'], unique=False)

    op.create_table('marketplace_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('prix_demande', sa.Float(), nullable=False),
    sa.Column('date_mise_en_vente', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketplace_listing')
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_index('ix_participant_race')

    op.drop_table('participant')
    op.drop_table('inventory_item')
    with op.batch_alter_table('course_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_plan_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_plan_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_course_plan_pig_id'))
        batch_op.drop_index(batch_op.f('ix_course_plan_created_at'))

    op.drop_table('course_plan')
    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_notification_event_key'))
        batch_op.drop_index(batch_op.f('ix_user_notification_created_at'))

    op.drop_table('user_notification')
    with op.batch_alter_table('trophy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trophy_user_id'))
        batch_op.drop_index(batch_op.f('ix_trophy_earned_at'))
        batch_op.drop_index(batch_op.f('ix_trophy_date_earned'))

    op.drop_table('trophy')
    with op.batch_alter_table('poker_player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poker_player_user_id'))
        batch_op.drop_index(batch_op.f('ix_poker_player_table_id'))

    op.drop_table('poker_player')
    with op.batch_alter_table('poker_hand_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poker_hand_history_table_id'))

    op.drop_table('poker_hand_history')
    with op.batch_alter_table('pig', schema=None) as batch_op:
        batch_op.drop_index('ix_pig_user_alive')

    op.drop_table('pig')
    op.drop_table('item')
    op.drop_table('grain_market')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_timestamp'))

    op.drop_table('chat_message')
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_index('ix_bet_user_race')

    op.drop_table('bet')
    with op.batch_alter_table('balance_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_balance_transaction_created_at'))

    op.drop_table('balance_transaction')
    with op.batch_alter_table('auth_event_log', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_event_type_time')
        batch_op.drop_index(batch_op.f('ix_auth_event_log_username_attempt'))
        batch_op.drop_index(batch_op.f('ix_auth_event_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_event_log_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_auth_event_log_ip_address'))

    op.drop_table('auth_event_log')
    op.drop_table('auction')
    op.drop_table('user')
    op.drop_table('training_item')
    op.drop_table('shop')
    op.drop_table('school_lesson_item')
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_index('ix_race_status_finished')

    op.drop_table('race')
    op.drop_table('poker_table')
    op.drop_table('pig_avatar')
    with op.batch_alter_table('market_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_history_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_market_history_cereal_key'))

    op.drop_table('market_history')
    op.drop_table('game_config')
    op.drop_table('cereal_item')
    # ### end Alembic commands ###
