"""Race engine tuning defaults."""

RACE_MAX_TURNS = 120

RACE_ATTACK_THRESHOLD = 71
RACE_NEUTRAL_MAX = 70
RACE_STRATEGY_ECONOMY_MIN_MULT = 0.72
RACE_STRATEGY_ATTACK_MAX_MULT = 1.18
RACE_STRATEGY_ECONOMY_RECOVERY = 2.2
RACE_STRATEGY_NEUTRAL_FATIGUE = 1.2
RACE_ATTACK_FATIGUE_EXPONENT = 1.6

RACE_BASE_SPEED_VIT_MULT = 0.75
RACE_BASE_SPEED_CONSTANT = 2.0
RACE_MIN_FINAL_SPEED = 0.5
RACE_SEGMENT_SPEED_CAP = 30.0
RACE_VIRAGE_SPEED_CAP = 18.0
RACE_BOUE_SPEED_CAP = 14.0

RACE_FATIGUE_SPEED_PENALTY_FLOOR = 0.4
RACE_FATIGUE_SPEED_PENALTY_DIVISOR = 100.0
RACE_ENDURANCE_FATIGUE_DIVISOR = 1.0
RACE_RECENT_RACE_PENALTY_FLOOR = 0.88

RACE_MONTEE_SPEED_MULT = 0.8
RACE_MONTEE_FORCE_MULT = 1.2
RACE_MONTEE_TERRAIN_MOD = 0.86

RACE_DESCENTE_SPEED_MULT = 0.95
RACE_DESCENTE_TERRAIN_MOD = 1.08
RACE_DESCENTE_AGI_RISK_REDUCTION = 140.0
RACE_STUMBLE_BASE_CHANCE_DESCENTE = 0.12
RACE_STUMBLE_SPEED_MULT = 0.5

RACE_STUMBLE_BASE_CHANCE_VIRAGE = 0.09
RACE_VIRAGE_AGI_MULT = 0.9
RACE_VIRAGE_TERRAIN_MOD = 0.88
RACE_BOUE_AGI_MULT = 0.75
RACE_BOUE_TERRAIN_MOD = 0.76

RACE_DRAFT_MIN_DIST = 1.0
RACE_DRAFT_MAX_DIST = 3.0
RACE_DRAFT_BONUS_MIN = 0.8
RACE_DRAFT_BONUS_MAX = 1.8
RACE_DRAFT_NO_FATIGUE_BONUS = 1.8
RACE_FATIGUE_HEADWIND_PENALTY = 0.8

RACE_VARIANCE_MIN = 0.98
RACE_VARIANCE_MAX = 1.02
